BEGIN	
	CREATE DATABASE BeStyleDB;
END;

GO
	USE BeStyleDB;
GO


BEGIN
	CREATE TABLE tblUser
		(	
			Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
			FirstName NVARCHAR(50) NOT NULL,
			LastName NVARCHAR(50) NOT NULL,
			Email NVARCHAR(50) NOT NULL UNIQUE,
			Phone NVARCHAR(50)			
		);
END;

BEGIN
	CREATE TABLE tblUserCredential
	(
		Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		UserId INT NOT NULL,
		Login NVARCHAR(50) NOT NULL UNIQUE,
		Password NVARCHAR(50) NOT NULL,
		CONSTRAINT FK_tblUserCredential_tblUserId FOREIGN KEY (UserId) REFERENCES tblUser(Id)		
	);
END;	

BEGIN
		CREATE TABLE tblAdmin
		(
			Id  INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
			FirstName NVARCHAR(50) NOT NULL,
			LastName NVARCHAR(50) NOT NULL,
			Email NVARCHAR(50) NOT NULL UNIQUE,
			Phone NVARCHAR(50)			
		);
END;

BEGIN
	CREATE TABLE tblAdminCredential
	(
		Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		AdminId INT NOT NULL,
		Login NVARCHAR(50) NOT NULL UNIQUE,
		Password NVARCHAR(50) NOT NULL,
		CONSTRAINT FK_tblAdminCredential_tblAdminId FOREIGN KEY (AdminId) REFERENCES tblAdmin(Id),
	);
END;